ssasia:
  data:
    datasource:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maxPoolSize: 10
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.0.160:3306/?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      schema: zedee_game
      username: zedee
      password: 1qazxsw2@!~
    vip:
      host: 58.82.247.16
      port: 8090
      version: V021
      username: Ss9211
      password: qwe123
      autoCreateEvent: false
      subscribeBookmakers:
      - 2
      - 5
      - 37
  kafka:
    bootstrapServers: 192.168.0.160:9092
    
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ssasia-data-odds
          contentType: application/json
          consumer:
            headerMode: raw
            autoOffsetReset: latest
        output:
          destination: ssasia-data-input
          contentType: application/json
          producer:
            headerMode: raw
        oddsOut:
          destination: ssasia-data-odds
          contentType: application/json
          producer:
            headerMode: raw
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
              offset.reset: latest
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
            autoCreateTopics: true
            autoOffsetReset: latest
            brokers:
              - 192.168.0.160
        binder:
          brokers:
            - 192.168.0.160
