ssasia:
  data:
    datasource:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maxPoolSize: 4
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://ssasia.cofpgalbezja.ap-northeast-1.rds.amazonaws.com:3306/?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      schema: zedee_game
      username: ssasia
      password: RdJNC5rtn6jcs4
    vip:
      host: 58.82.247.16
      port: 8090
      version: V021
      username: Ss9211
      password: qwe123
      autoCreateEvents: false
      subscribeBookmakers:
      - 2
  kafka:
    bootstrapServers: 192.168.0.160:9092
    
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ssasia-data-odds
          contentType: application/json
          consumer:
            headerMode: raw
            resetOffsets: true
            startOffset: latest
        output:
          destination: ssasia-data-input
          contentType: application/json
          producer:
            headerMode: raw
        outputInplay:
          destination: ssasia-odds-inplay
          contentType: application/json
          producer:
            headerMode: raw
        oddsOut:
          destination: ssasia-data-odds
          contentType: application/json
          producer:
            headerMode: raw
      kafka:
        streams:
          binder:
            application-id: odds-service
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
            autoCreateTopics: true
            brokers:
              - 192.168.0.160
        binder:
          brokers:
            - 192.168.0.160
