ssasia:
  data:
    datasource:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maxPoolSize: 10
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://prodssasia.cofpgalbezja.ap-northeast-1.rds.amazonaws.com:3306/?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&noAccessToProcedureBodies=true
      schema: zedee_game
      username: zedee
      password: 5BmJNC5n6jcs4JF5
  bo:
    uri: http://10.188.129.173:8082/restful
    username: AUTO-PRICING
    token: c523d59fc61211e7bd7a6c0b840c4dc4

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ssasia-data-input
          group: group_pricing
          contentType: application/json
          consumer:
            headerMode: raw
        output:
          destination: ssasia-data-output
          contentType: application/json
          producer:
            headerMode: raw
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
            autoCreateTopics: true
            brokers:
              - 10.188.129.251
        binder:
          brokers:
            - 10.188.129.251
